SELECT b.FLIGHT_DATE AS FlightDate, dep_a.CITY AS DepartingCity, arr_a.CITY AS ArrivingCity
FROM BOOKINGS AS b
JOIN FLIGHTS AS f ON b.FLIGHT_NUMBER = f.FNUMBER
JOIN AIRPORTS AS dep_a ON f.DEP_AIRPORT = dep_a.CODE
JOIN AIRPORTS AS arr_a ON f.ARR_AIRPORT = arr_a.CODE
WHERE b.CUSTOMER_ID = (SELECT ID FROM CUSTOMERS WHERE FNAME = 'Petar' AND LNAME = 'Milenov')
ORDER BY FLIGHT_DATE;