SELECT * FROM BOOKINGS;
SELECT * FROM CUSTOMERS;

--SELECT FNAME, LNAME FROM CUSTOMERS AS c
--WHERE c.ID = (SELECT MIN(BOOKING_DATE)

SELECT FNAME, LNAME FROM CUSTOMERS AS c
WHERE YEAR((SELECT MIN(BOOKING_DATE) FROM BOOKINGS as b WHERE b.CUSTOMER_ID = 1)) % 2 = 1;
