CREATE TABLE Sellers (
	Id INT IDENTITY,
	[Name] NCHAR(50),
	Website NCHAR(50),
	Email NCHAR(50),
	PRIMARY KEY(Id)
);

INSERT INTO Sellers ([Name], Website, Email) VALUES
('TechTrend', 'www.techtrend.com', 'info@techtrend.com'),
('FashionFusion', 'www.fashionfusion.com', 'info@fashionfusion.com'),
('GardenGalore', 'www.gardengalore.com', 'info@gardengalore.com'),
('BeautyBliss', 'www.beautybliss.com', 'info@beautybliss.com'),
('SportSpot', 'www.sportspot.com', 'info@sportspot.com'),
('NoveltyNook', 'www.noveltynook.com', 'info@noveltynook.com'),
('ToyTime', 'www.toytime.com', 'info@toytime.com'),
('AutoAvenue', 'www.autoavenue.com', 'info@autoavenue.com'),
('PetParadise', 'www.petparadise.com', 'info@petparadise.com'),
('OfficeOasis', 'www.officeoasis.com', 'info@officeoasis.com'),
('KitchenKraft', 'www.kitchenkraft.com', 'info@kitchenkraft.com'),
('ShoeShack', 'www.shoeshack.com', 'info@shoeshack.com'),
('ArtisanAlley', 'www.artisanalley.com', 'info@artisanalley.com'),
('BikeBoutique', 'www.bikeboutique.com', 'info@bikeboutique.com'),
('MusicMania', 'www.musicmania.com', 'info@musicmania.com'),
('SweetSensations', 'www.sweetsensations.com', 'info@sweetsensations.com'),
('FitnessFusion', 'www.fitnessfusion.com', 'info@fitnessfusion.com'),
('HomeHaven', 'www.homehaven.com', 'info@homehaven.com'),
('WellnessWorld', 'www.wellnessworld.com', 'info@wellnessworld.com'),
('CraftyCorner', 'www.craftycorner.com', 'info@craftycorner.com'),
('TravelTreasures', 'www.traveltreasures.com', 'info@traveltreasures.com'),
('BabyBoutique', 'www.babyboutique.com', 'info@babyboutique.com'),
('OutdoorOasis', 'www.outdooroasis.com', 'info@outdooroasis.com'),
('DIYDepot', 'www.diydepot.com', 'info@diydepot.com'),
('EcoEssentials', 'www.ecoessentials.com', 'info@ecoessentials.com'),
('BookwormBazaar', 'www.bookwormbazaar.com', 'info@bookwormbazaar.com'),
('TechSavvySolutions', 'www.techsavvysolutions.com', 'info@techsavvysolutions.com'),
('FashionForwardFinds', 'www.fashionforwardfinds.com', 'info@fashionforwardfinds.com'),
('PetPamperPalace', 'www.petpamperpalace.com', 'info@petpamperpalace.com'),
('CulinaryCraze', 'www.culinarycraze.com', 'info@culinarycraze.com');